/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiesgosRouteImport } from './routes/riesgos'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as ProcesosRouteImport } from './routes/procesos'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as GuardianRouteImport } from './routes/guardian'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as DocumentacionRouteImport } from './routes/documentacion'
import { Route as CronogramaRouteImport } from './routes/cronograma'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const RiesgosRoute = RiesgosRouteImport.update({
    id: '/riesgos',
    path: '/riesgos',
    getParentRoute: () => rootRouteImport,
} as any)
const ProveedoresRoute = ProveedoresRouteImport.update({
    id: '/proveedores',
    path: '/proveedores',
    getParentRoute: () => rootRouteImport,
} as any)
const ProcesosRoute = ProcesosRouteImport.update({
    id: '/procesos',
    path: '/procesos',
    getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => rootRouteImport,
} as any)
const GuardianRoute = GuardianRouteImport.update({
    id: '/guardian',
    path: '/guardian',
    getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
    id: '/equipo',
    path: '/equipo',
    getParentRoute: () => rootRouteImport,
} as any)
const DocumentacionRoute = DocumentacionRouteImport.update({
    id: '/documentacion',
    path: '/documentacion',
    getParentRoute: () => rootRouteImport,
} as any)
const CronogramaRoute = CronogramaRouteImport.update({
    id: '/cronograma',
    path: '/cronograma',
    getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
    id: '/contratos',
    path: '/contratos',
    getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
    id: '/api/chat',
    path: '/api/chat',
    getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute
    '/chat': typeof ChatRoute
    '/clientes': typeof ClientesRoute
    '/configuracion': typeof ConfiguracionRoute
    '/contratos': typeof ContratosRoute
    '/cronograma': typeof CronogramaRoute
    '/documentacion': typeof DocumentacionRoute
    '/equipo': typeof EquipoRoute
    '/guardian': typeof GuardianRoute
    '/indicadores': typeof IndicadoresRoute
    '/procesos': typeof ProcesosRoute
    '/proveedores': typeof ProveedoresRoute
    '/riesgos': typeof RiesgosRoute
    '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
    '/': typeof IndexRoute
    '/chat': typeof ChatRoute
    '/clientes': typeof ClientesRoute
    '/configuracion': typeof ConfiguracionRoute
    '/contratos': typeof ContratosRoute
    '/cronograma': typeof CronogramaRoute
    '/documentacion': typeof DocumentacionRoute
    '/equipo': typeof EquipoRoute
    '/guardian': typeof GuardianRoute
    '/indicadores': typeof IndicadoresRoute
    '/procesos': typeof ProcesosRoute
    '/proveedores': typeof ProveedoresRoute
    '/riesgos': typeof RiesgosRoute
    '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport
    '/': typeof IndexRoute
    '/chat': typeof ChatRoute
    '/clientes': typeof ClientesRoute
    '/configuracion': typeof ConfiguracionRoute
    '/contratos': typeof ContratosRoute
    '/cronograma': typeof CronogramaRoute
    '/documentacion': typeof DocumentacionRoute
    '/equipo': typeof EquipoRoute
    '/guardian': typeof GuardianRoute
    '/indicadores': typeof IndicadoresRoute
    '/procesos': typeof ProcesosRoute
    '/proveedores': typeof ProveedoresRoute
    '/riesgos': typeof RiesgosRoute
    '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths:
    | '/'
    | '/chat'
    | '/clientes'
    | '/configuracion'
    | '/contratos'
    | '/cronograma'
    | '/documentacion'
    | '/equipo'
    | '/guardian'
    | '/indicadores'
    | '/procesos'
    | '/proveedores'
    | '/riesgos'
    | '/api/chat'
    fileRoutesByTo: FileRoutesByTo
    to:
    | '/'
    | '/chat'
    | '/clientes'
    | '/configuracion'
    | '/contratos'
    | '/cronograma'
    | '/documentacion'
    | '/equipo'
    | '/guardian'
    | '/indicadores'
    | '/procesos'
    | '/proveedores'
    | '/riesgos'
    | '/api/chat'
    id:
    | '__root__'
    | '/'
    | '/chat'
    | '/clientes'
    | '/configuracion'
    | '/contratos'
    | '/cronograma'
    | '/documentacion'
    | '/equipo'
    | '/guardian'
    | '/indicadores'
    | '/procesos'
    | '/proveedores'
    | '/riesgos'
    | '/api/chat'
    fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute
    ChatRoute: typeof ChatRoute
    ClientesRoute: typeof ClientesRoute
    ConfiguracionRoute: typeof ConfiguracionRoute
    ContratosRoute: typeof ContratosRoute
    CronogramaRoute: typeof CronogramaRoute
    DocumentacionRoute: typeof DocumentacionRoute
    EquipoRoute: typeof EquipoRoute
    GuardianRoute: typeof GuardianRoute
    IndicadoresRoute: typeof IndicadoresRoute
    ProcesosRoute: typeof ProcesosRoute
    ProveedoresRoute: typeof ProveedoresRoute
    RiesgosRoute: typeof RiesgosRoute
    ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/riesgos': {
            id: '/riesgos'
            path: '/riesgos'
            fullPath: '/riesgos'
            preLoaderRoute: typeof RiesgosRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/proveedores': {
            id: '/proveedores'
            path: '/proveedores'
            fullPath: '/proveedores'
            preLoaderRoute: typeof ProveedoresRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/procesos': {
            id: '/procesos'
            path: '/procesos'
            fullPath: '/procesos'
            preLoaderRoute: typeof ProcesosRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/indicadores': {
            id: '/indicadores'
            path: '/indicadores'
            fullPath: '/indicadores'
            preLoaderRoute: typeof IndicadoresRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/guardian': {
            id: '/guardian'
            path: '/guardian'
            fullPath: '/guardian'
            preLoaderRoute: typeof GuardianRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/equipo': {
            id: '/equipo'
            path: '/equipo'
            fullPath: '/equipo'
            preLoaderRoute: typeof EquipoRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/documentacion': {
            id: '/documentacion'
            path: '/documentacion'
            fullPath: '/documentacion'
            preLoaderRoute: typeof DocumentacionRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/cronograma': {
            id: '/cronograma'
            path: '/cronograma'
            fullPath: '/cronograma'
            preLoaderRoute: typeof CronogramaRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/contratos': {
            id: '/contratos'
            path: '/contratos'
            fullPath: '/contratos'
            preLoaderRoute: typeof ContratosRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/configuracion': {
            id: '/configuracion'
            path: '/configuracion'
            fullPath: '/configuracion'
            preLoaderRoute: typeof ConfiguracionRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/clientes': {
            id: '/clientes'
            path: '/clientes'
            fullPath: '/clientes'
            preLoaderRoute: typeof ClientesRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/chat': {
            id: '/chat'
            path: '/chat'
            fullPath: '/chat'
            preLoaderRoute: typeof ChatRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/': {
            id: '/'
            path: '/'
            fullPath: '/'
            preLoaderRoute: typeof IndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/api/chat': {
            id: '/api/chat'
            path: '/api/chat'
            fullPath: '/api/chat'
            preLoaderRoute: typeof ApiChatRouteImport
            parentRoute: typeof rootRouteImport
        }
    }
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    ChatRoute: ChatRoute,
    ClientesRoute: ClientesRoute,
    ConfiguracionRoute: ConfiguracionRoute,
    ContratosRoute: ContratosRoute,
    CronogramaRoute: CronogramaRoute,
    DocumentacionRoute: DocumentacionRoute,
    EquipoRoute: EquipoRoute,
    GuardianRoute: GuardianRoute,
    IndicadoresRoute: IndicadoresRoute,
    ProcesosRoute: ProcesosRoute,
    ProveedoresRoute: ProveedoresRoute,
    RiesgosRoute: RiesgosRoute,
    ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
    interface Register {
        ssr: true
        router: Awaited<ReturnType<typeof getRouter>>
        config: Awaited<ReturnType<typeof startInstance.getOptions>>
    }
}
