/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedCronogramaRouteImport } from './routes/_authenticated/cronograma'
import { Route as AuthenticatedEquipoRouteImport } from './routes/_authenticated/equipo'
import { Route as AuthenticatedGuardianRouteImport } from './routes/_authenticated/guardian'
import { Route as AuthenticatedIndicadoresRouteImport } from './routes/_authenticated/indicadores'
import { Route as AuthenticatedProveedoresRouteImport } from './routes/_authenticated/proveedores'
import { Route as AuthenticatedRiesgosRouteImport } from './routes/_authenticated/riesgos'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiHallazgosRouteImport } from './routes/api/hallazgos'
import { Route as ApiNotificacionesRouteImport } from './routes/api/notificaciones'
import { Route as ApiWikiChatRouteImport } from './routes/api/wiki-chat'
import { Route as AuthenticatedProcesosIndexRouteImport } from './routes/_authenticated/procesos/index'
import { Route as AuthenticatedProcesosVulnerabilidadesRouteImport } from './routes/_authenticated/procesos/vulnerabilidades'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiSyncClientesRouteImport } from './routes/api/sync/clientes'
import { Route as ApiSyncDocumentacionRouteImport } from './routes/api/sync/documentacion'
import { Route as ApiSyncRiesgosRouteImport } from './routes/api/sync/riesgos'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCronogramaRoute = AuthenticatedCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipoRoute = AuthenticatedEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuardianRoute = AuthenticatedGuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIndicadoresRoute =
  AuthenticatedIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProveedoresRoute =
  AuthenticatedProveedoresRouteImport.update({
    id: '/proveedores',
    path: '/proveedores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRiesgosRoute = AuthenticatedRiesgosRouteImport.update({
  id: '/riesgos',
  path: '/riesgos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHallazgosRoute = ApiHallazgosRouteImport.update({
  id: '/api/hallazgos',
  path: '/api/hallazgos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificacionesRoute = ApiNotificacionesRouteImport.update({
  id: '/api/notificaciones',
  path: '/api/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWikiChatRoute = ApiWikiChatRouteImport.update({
  id: '/api/wiki-chat',
  path: '/api/wiki-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProcesosIndexRoute =
  AuthenticatedProcesosIndexRouteImport.update({
    id: '/procesos/',
    path: '/procesos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProcesosVulnerabilidadesRoute =
  AuthenticatedProcesosVulnerabilidadesRouteImport.update({
    id: '/procesos/vulnerabilidades',
    path: '/procesos/vulnerabilidades',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncClientesRoute = ApiSyncClientesRouteImport.update({
  id: '/api/sync/clientes',
  path: '/api/sync/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncDocumentacionRoute = ApiSyncDocumentacionRouteImport.update({
  id: '/api/sync/documentacion',
  path: '/api/sync/documentacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRiesgosRoute = ApiSyncRiesgosRouteImport.update({
  id: '/api/sync/riesgos',
  path: '/api/sync/riesgos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/chat': typeof AuthenticatedChatRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/equipo': typeof AuthenticatedEquipoRoute
  '/guardian': typeof AuthenticatedGuardianRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/riesgos': typeof AuthenticatedRiesgosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hallazgos': typeof ApiHallazgosRoute
  '/api/notificaciones': typeof ApiNotificacionesRoute
  '/api/wiki-chat': typeof ApiWikiChatRoute
  '/procesos/vulnerabilidades': typeof AuthenticatedProcesosVulnerabilidadesRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/sync/clientes': typeof ApiSyncClientesRoute
  '/api/sync/documentacion': typeof ApiSyncDocumentacionRoute
  '/api/sync/riesgos': typeof ApiSyncRiesgosRoute
  '/procesos/': typeof AuthenticatedProcesosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/chat': typeof AuthenticatedChatRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/equipo': typeof AuthenticatedEquipoRoute
  '/guardian': typeof AuthenticatedGuardianRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/riesgos': typeof AuthenticatedRiesgosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hallazgos': typeof ApiHallazgosRoute
  '/api/notificaciones': typeof ApiNotificacionesRoute
  '/api/wiki-chat': typeof ApiWikiChatRoute
  '/': typeof AuthenticatedIndexRoute
  '/procesos/vulnerabilidades': typeof AuthenticatedProcesosVulnerabilidadesRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/sync/clientes': typeof ApiSyncClientesRoute
  '/api/sync/documentacion': typeof ApiSyncDocumentacionRoute
  '/api/sync/riesgos': typeof ApiSyncRiesgosRoute
  '/procesos': typeof AuthenticatedProcesosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/cronograma': typeof AuthenticatedCronogramaRoute
  '/_authenticated/equipo': typeof AuthenticatedEquipoRoute
  '/_authenticated/guardian': typeof AuthenticatedGuardianRoute
  '/_authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/_authenticated/proveedores': typeof AuthenticatedProveedoresRoute
  '/_authenticated/riesgos': typeof AuthenticatedRiesgosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hallazgos': typeof ApiHallazgosRoute
  '/api/notificaciones': typeof ApiNotificacionesRoute
  '/api/wiki-chat': typeof ApiWikiChatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/procesos/vulnerabilidades': typeof AuthenticatedProcesosVulnerabilidadesRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/sync/clientes': typeof ApiSyncClientesRoute
  '/api/sync/documentacion': typeof ApiSyncDocumentacionRoute
  '/api/sync/riesgos': typeof ApiSyncRiesgosRoute
  '/_authenticated/procesos/': typeof AuthenticatedProcesosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/chat'
    | '/clientes'
    | '/configuracion'
    | '/cronograma'
    | '/equipo'
    | '/guardian'
    | '/indicadores'
    | '/proveedores'
    | '/riesgos'
    | '/api/chat'
    | '/api/hallazgos'
    | '/api/notificaciones'
    | '/api/wiki-chat'
    | '/procesos/vulnerabilidades'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/sync/clientes'
    | '/api/sync/documentacion'
    | '/api/sync/riesgos'
    | '/procesos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/chat'
    | '/clientes'
    | '/configuracion'
    | '/cronograma'
    | '/equipo'
    | '/guardian'
    | '/indicadores'
    | '/proveedores'
    | '/riesgos'
    | '/api/chat'
    | '/api/hallazgos'
    | '/api/notificaciones'
    | '/api/wiki-chat'
    | '/'
    | '/procesos/vulnerabilidades'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/sync/clientes'
    | '/api/sync/documentacion'
    | '/api/sync/riesgos'
    | '/procesos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/chat'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracion'
    | '/_authenticated/cronograma'
    | '/_authenticated/equipo'
    | '/_authenticated/guardian'
    | '/_authenticated/indicadores'
    | '/_authenticated/proveedores'
    | '/_authenticated/riesgos'
    | '/api/chat'
    | '/api/hallazgos'
    | '/api/notificaciones'
    | '/api/wiki-chat'
    | '/_authenticated/'
    | '/_authenticated/procesos/vulnerabilidades'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/sync/clientes'
    | '/api/sync/documentacion'
    | '/api/sync/riesgos'
    | '/_authenticated/procesos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHallazgosRoute: typeof ApiHallazgosRoute
  ApiNotificacionesRoute: typeof ApiNotificacionesRoute
  ApiWikiChatRoute: typeof ApiWikiChatRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiSyncClientesRoute: typeof ApiSyncClientesRoute
  ApiSyncDocumentacionRoute: typeof ApiSyncDocumentacionRoute
  ApiSyncRiesgosRoute: typeof ApiSyncRiesgosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cronograma': {
      id: '/_authenticated/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof AuthenticatedCronogramaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipo': {
      id: '/_authenticated/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AuthenticatedEquipoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guardian': {
      id: '/_authenticated/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof AuthenticatedGuardianRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/indicadores': {
      id: '/_authenticated/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof AuthenticatedIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proveedores': {
      id: '/_authenticated/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof AuthenticatedProveedoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/riesgos': {
      id: '/_authenticated/riesgos'
      path: '/riesgos'
      fullPath: '/riesgos'
      preLoaderRoute: typeof AuthenticatedRiesgosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hallazgos': {
      id: '/api/hallazgos'
      path: '/api/hallazgos'
      fullPath: '/api/hallazgos'
      preLoaderRoute: typeof ApiHallazgosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notificaciones': {
      id: '/api/notificaciones'
      path: '/api/notificaciones'
      fullPath: '/api/notificaciones'
      preLoaderRoute: typeof ApiNotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wiki-chat': {
      id: '/api/wiki-chat'
      path: '/api/wiki-chat'
      fullPath: '/api/wiki-chat'
      preLoaderRoute: typeof ApiWikiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/procesos/': {
      id: '/_authenticated/procesos/'
      path: '/procesos'
      fullPath: '/procesos/'
      preLoaderRoute: typeof AuthenticatedProcesosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/procesos/vulnerabilidades': {
      id: '/_authenticated/procesos/vulnerabilidades'
      path: '/procesos/vulnerabilidades'
      fullPath: '/procesos/vulnerabilidades'
      preLoaderRoute: typeof AuthenticatedProcesosVulnerabilidadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/clientes': {
      id: '/api/sync/clientes'
      path: '/api/sync/clientes'
      fullPath: '/api/sync/clientes'
      preLoaderRoute: typeof ApiSyncClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/documentacion': {
      id: '/api/sync/documentacion'
      path: '/api/sync/documentacion'
      fullPath: '/api/sync/documentacion'
      preLoaderRoute: typeof ApiSyncDocumentacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/riesgos': {
      id: '/api/sync/riesgos'
      path: '/api/sync/riesgos'
      fullPath: '/api/sync/riesgos'
      preLoaderRoute: typeof ApiSyncRiesgosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedCronogramaRoute: typeof AuthenticatedCronogramaRoute
  AuthenticatedEquipoRoute: typeof AuthenticatedEquipoRoute
  AuthenticatedGuardianRoute: typeof AuthenticatedGuardianRoute
  AuthenticatedIndicadoresRoute: typeof AuthenticatedIndicadoresRoute
  AuthenticatedProveedoresRoute: typeof AuthenticatedProveedoresRoute
  AuthenticatedRiesgosRoute: typeof AuthenticatedRiesgosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProcesosVulnerabilidadesRoute: typeof AuthenticatedProcesosVulnerabilidadesRoute
  AuthenticatedProcesosIndexRoute: typeof AuthenticatedProcesosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedCronogramaRoute: AuthenticatedCronogramaRoute,
  AuthenticatedEquipoRoute: AuthenticatedEquipoRoute,
  AuthenticatedGuardianRoute: AuthenticatedGuardianRoute,
  AuthenticatedIndicadoresRoute: AuthenticatedIndicadoresRoute,
  AuthenticatedProveedoresRoute: AuthenticatedProveedoresRoute,
  AuthenticatedRiesgosRoute: AuthenticatedRiesgosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProcesosVulnerabilidadesRoute:
    AuthenticatedProcesosVulnerabilidadesRoute,
  AuthenticatedProcesosIndexRoute: AuthenticatedProcesosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHallazgosRoute: ApiHallazgosRoute,
  ApiNotificacionesRoute: ApiNotificacionesRoute,
  ApiWikiChatRoute: ApiWikiChatRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiSyncClientesRoute: ApiSyncClientesRoute,
  ApiSyncDocumentacionRoute: ApiSyncDocumentacionRoute,
  ApiSyncRiesgosRoute: ApiSyncRiesgosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
