/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedCronogramaRouteImport } from './routes/_authenticated/cronograma'
import { Route as AuthenticatedEquipoRouteImport } from './routes/_authenticated/equipo'
import { Route as AuthenticatedIndicadoresRouteImport } from './routes/_authenticated/indicadores'
import { Route as AuthenticatedNormasRouteImport } from './routes/_authenticated/normas'
import { Route as AuthenticatedProveedoresRouteImport } from './routes/_authenticated/proveedores'
import { Route as AuthenticatedRiesgosRouteImport } from './routes/_authenticated/riesgos'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiChecklistClientesEstadoRouteImport } from './routes/api/checklist-clientes-estado'
import { Route as ApiHallazgosRouteImport } from './routes/api/hallazgos'
import { Route as ApiNotificacionesRouteImport } from './routes/api/notificaciones'
import { Route as ApiSigActualizacionesRouteImport } from './routes/api/sig-actualizaciones'
import { Route as ApiWikiChatRouteImport } from './routes/api/wiki-chat'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes/index'
import { Route as AuthenticatedClientesDocumentacionRouteImport } from './routes/_authenticated/clientes/documentacion'
import { Route as AuthenticatedCulturaIndexRouteImport } from './routes/_authenticated/cultura/index'
import { Route as AuthenticatedCulturaConceptosRouteImport } from './routes/_authenticated/cultura/conceptos'
import { Route as AuthenticatedCulturaObjetivosRouteImport } from './routes/_authenticated/cultura/objetivos'
import { Route as AuthenticatedCulturaPoliticasRouteImport } from './routes/_authenticated/cultura/politicas'
import { Route as AuthenticatedGuardianIndexRouteImport } from './routes/_authenticated/guardian/index'
import { Route as AuthenticatedGuardianHallazgosRouteImport } from './routes/_authenticated/guardian/hallazgos'
import { Route as AuthenticatedProcesosIndexRouteImport } from './routes/_authenticated/procesos/index'
import { Route as AuthenticatedProcesosRevisionRouteImport } from './routes/_authenticated/procesos/revision'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiMePhotoRouteImport } from './routes/api/me/photo'
import { Route as ApiSyncChecklistClientesRouteImport } from './routes/api/sync/checklist-clientes'
import { Route as ApiSyncClientesRouteImport } from './routes/api/sync/clientes'
import { Route as ApiSyncDocumentacionRouteImport } from './routes/api/sync/documentacion'
import { Route as ApiSyncIndicadorDisponibilidadRouteImport } from './routes/api/sync/indicador-disponibilidad'
import { Route as ApiSyncProveedoresRouteImport } from './routes/api/sync/proveedores'
import { Route as ApiSyncRiesgosRouteImport } from './routes/api/sync/riesgos'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCronogramaRoute = AuthenticatedCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipoRoute = AuthenticatedEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIndicadoresRoute =
  AuthenticatedIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNormasRoute = AuthenticatedNormasRouteImport.update({
  id: '/normas',
  path: '/normas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProveedoresRoute =
  AuthenticatedProveedoresRouteImport.update({
    id: '/proveedores',
    path: '/proveedores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRiesgosRoute = AuthenticatedRiesgosRouteImport.update({
  id: '/riesgos',
  path: '/riesgos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChecklistClientesEstadoRoute =
  ApiChecklistClientesEstadoRouteImport.update({
    id: '/api/checklist-clientes-estado',
    path: '/api/checklist-clientes-estado',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHallazgosRoute = ApiHallazgosRouteImport.update({
  id: '/api/hallazgos',
  path: '/api/hallazgos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificacionesRoute = ApiNotificacionesRouteImport.update({
  id: '/api/notificaciones',
  path: '/api/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSigActualizacionesRoute = ApiSigActualizacionesRouteImport.update({
  id: '/api/sig-actualizaciones',
  path: '/api/sig-actualizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWikiChatRoute = ApiWikiChatRouteImport.update({
  id: '/api/wiki-chat',
  path: '/api/wiki-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesDocumentacionRoute =
  AuthenticatedClientesDocumentacionRouteImport.update({
    id: '/clientes/documentacion',
    path: '/clientes/documentacion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCulturaIndexRoute =
  AuthenticatedCulturaIndexRouteImport.update({
    id: '/cultura/',
    path: '/cultura/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCulturaConceptosRoute =
  AuthenticatedCulturaConceptosRouteImport.update({
    id: '/cultura/conceptos',
    path: '/cultura/conceptos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCulturaObjetivosRoute =
  AuthenticatedCulturaObjetivosRouteImport.update({
    id: '/cultura/objetivos',
    path: '/cultura/objetivos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCulturaPoliticasRoute =
  AuthenticatedCulturaPoliticasRouteImport.update({
    id: '/cultura/politicas',
    path: '/cultura/politicas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGuardianIndexRoute =
  AuthenticatedGuardianIndexRouteImport.update({
    id: '/guardian/',
    path: '/guardian/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGuardianHallazgosRoute =
  AuthenticatedGuardianHallazgosRouteImport.update({
    id: '/guardian/hallazgos',
    path: '/guardian/hallazgos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProcesosIndexRoute =
  AuthenticatedProcesosIndexRouteImport.update({
    id: '/procesos/',
    path: '/procesos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProcesosRevisionRoute =
  AuthenticatedProcesosRevisionRouteImport.update({
    id: '/procesos/revision',
    path: '/procesos/revision',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMePhotoRoute = ApiMePhotoRouteImport.update({
  id: '/api/me/photo',
  path: '/api/me/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncChecklistClientesRoute =
  ApiSyncChecklistClientesRouteImport.update({
    id: '/api/sync/checklist-clientes',
    path: '/api/sync/checklist-clientes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSyncClientesRoute = ApiSyncClientesRouteImport.update({
  id: '/api/sync/clientes',
  path: '/api/sync/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncDocumentacionRoute = ApiSyncDocumentacionRouteImport.update({
  id: '/api/sync/documentacion',
  path: '/api/sync/documentacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncIndicadorDisponibilidadRoute =
  ApiSyncIndicadorDisponibilidadRouteImport.update({
    id: '/api/sync/indicador-disponibilidad',
    path: '/api/sync/indicador-disponibilidad',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSyncProveedoresRoute = ApiSyncProveedoresRouteImport.update({
  id: '/api/sync/proveedores',
  path: '/api/sync/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRiesgosRoute = ApiSyncRiesgosRouteImport.update({
  id: '/api/sync/riesgos',
  path: '/api/sync/riesgos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/chat': typeof AuthenticatedChatRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/equipo': typeof AuthenticatedEquipoRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/normas': typeof AuthenticatedNormasRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/riesgos': typeof AuthenticatedRiesgosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/checklist-clientes-estado': typeof ApiChecklistClientesEstadoRoute
  '/api/hallazgos': typeof ApiHallazgosRoute
  '/api/notificaciones': typeof ApiNotificacionesRoute
  '/api/sig-actualizaciones': typeof ApiSigActualizacionesRoute
  '/api/wiki-chat': typeof ApiWikiChatRoute
  '/clientes/documentacion': typeof AuthenticatedClientesDocumentacionRoute
  '/cultura/conceptos': typeof AuthenticatedCulturaConceptosRoute
  '/cultura/objetivos': typeof AuthenticatedCulturaObjetivosRoute
  '/cultura/politicas': typeof AuthenticatedCulturaPoliticasRoute
  '/guardian/hallazgos': typeof AuthenticatedGuardianHallazgosRoute
  '/procesos/revision': typeof AuthenticatedProcesosRevisionRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/me/photo': typeof ApiMePhotoRoute
  '/api/sync/checklist-clientes': typeof ApiSyncChecklistClientesRoute
  '/api/sync/clientes': typeof ApiSyncClientesRoute
  '/api/sync/documentacion': typeof ApiSyncDocumentacionRoute
  '/api/sync/indicador-disponibilidad': typeof ApiSyncIndicadorDisponibilidadRoute
  '/api/sync/proveedores': typeof ApiSyncProveedoresRoute
  '/api/sync/riesgos': typeof ApiSyncRiesgosRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/cultura/': typeof AuthenticatedCulturaIndexRoute
  '/guardian/': typeof AuthenticatedGuardianIndexRoute
  '/procesos/': typeof AuthenticatedProcesosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/chat': typeof AuthenticatedChatRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/equipo': typeof AuthenticatedEquipoRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/normas': typeof AuthenticatedNormasRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/riesgos': typeof AuthenticatedRiesgosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/checklist-clientes-estado': typeof ApiChecklistClientesEstadoRoute
  '/api/hallazgos': typeof ApiHallazgosRoute
  '/api/notificaciones': typeof ApiNotificacionesRoute
  '/api/sig-actualizaciones': typeof ApiSigActualizacionesRoute
  '/api/wiki-chat': typeof ApiWikiChatRoute
  '/': typeof AuthenticatedIndexRoute
  '/clientes/documentacion': typeof AuthenticatedClientesDocumentacionRoute
  '/cultura/conceptos': typeof AuthenticatedCulturaConceptosRoute
  '/cultura/objetivos': typeof AuthenticatedCulturaObjetivosRoute
  '/cultura/politicas': typeof AuthenticatedCulturaPoliticasRoute
  '/guardian/hallazgos': typeof AuthenticatedGuardianHallazgosRoute
  '/procesos/revision': typeof AuthenticatedProcesosRevisionRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/me/photo': typeof ApiMePhotoRoute
  '/api/sync/checklist-clientes': typeof ApiSyncChecklistClientesRoute
  '/api/sync/clientes': typeof ApiSyncClientesRoute
  '/api/sync/documentacion': typeof ApiSyncDocumentacionRoute
  '/api/sync/indicador-disponibilidad': typeof ApiSyncIndicadorDisponibilidadRoute
  '/api/sync/proveedores': typeof ApiSyncProveedoresRoute
  '/api/sync/riesgos': typeof ApiSyncRiesgosRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/cultura': typeof AuthenticatedCulturaIndexRoute
  '/guardian': typeof AuthenticatedGuardianIndexRoute
  '/procesos': typeof AuthenticatedProcesosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/cronograma': typeof AuthenticatedCronogramaRoute
  '/_authenticated/equipo': typeof AuthenticatedEquipoRoute
  '/_authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/_authenticated/normas': typeof AuthenticatedNormasRoute
  '/_authenticated/proveedores': typeof AuthenticatedProveedoresRoute
  '/_authenticated/riesgos': typeof AuthenticatedRiesgosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/checklist-clientes-estado': typeof ApiChecklistClientesEstadoRoute
  '/api/hallazgos': typeof ApiHallazgosRoute
  '/api/notificaciones': typeof ApiNotificacionesRoute
  '/api/sig-actualizaciones': typeof ApiSigActualizacionesRoute
  '/api/wiki-chat': typeof ApiWikiChatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clientes/documentacion': typeof AuthenticatedClientesDocumentacionRoute
  '/_authenticated/cultura/conceptos': typeof AuthenticatedCulturaConceptosRoute
  '/_authenticated/cultura/objetivos': typeof AuthenticatedCulturaObjetivosRoute
  '/_authenticated/cultura/politicas': typeof AuthenticatedCulturaPoliticasRoute
  '/_authenticated/guardian/hallazgos': typeof AuthenticatedGuardianHallazgosRoute
  '/_authenticated/procesos/revision': typeof AuthenticatedProcesosRevisionRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/me/photo': typeof ApiMePhotoRoute
  '/api/sync/checklist-clientes': typeof ApiSyncChecklistClientesRoute
  '/api/sync/clientes': typeof ApiSyncClientesRoute
  '/api/sync/documentacion': typeof ApiSyncDocumentacionRoute
  '/api/sync/indicador-disponibilidad': typeof ApiSyncIndicadorDisponibilidadRoute
  '/api/sync/proveedores': typeof ApiSyncProveedoresRoute
  '/api/sync/riesgos': typeof ApiSyncRiesgosRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/cultura/': typeof AuthenticatedCulturaIndexRoute
  '/_authenticated/guardian/': typeof AuthenticatedGuardianIndexRoute
  '/_authenticated/procesos/': typeof AuthenticatedProcesosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/chat'
    | '/configuracion'
    | '/cronograma'
    | '/equipo'
    | '/indicadores'
    | '/normas'
    | '/proveedores'
    | '/riesgos'
    | '/api/chat'
    | '/api/checklist-clientes-estado'
    | '/api/hallazgos'
    | '/api/notificaciones'
    | '/api/sig-actualizaciones'
    | '/api/wiki-chat'
    | '/clientes/documentacion'
    | '/cultura/conceptos'
    | '/cultura/objetivos'
    | '/cultura/politicas'
    | '/guardian/hallazgos'
    | '/procesos/revision'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/me/photo'
    | '/api/sync/checklist-clientes'
    | '/api/sync/clientes'
    | '/api/sync/documentacion'
    | '/api/sync/indicador-disponibilidad'
    | '/api/sync/proveedores'
    | '/api/sync/riesgos'
    | '/clientes/'
    | '/cultura/'
    | '/guardian/'
    | '/procesos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/chat'
    | '/configuracion'
    | '/cronograma'
    | '/equipo'
    | '/indicadores'
    | '/normas'
    | '/proveedores'
    | '/riesgos'
    | '/api/chat'
    | '/api/checklist-clientes-estado'
    | '/api/hallazgos'
    | '/api/notificaciones'
    | '/api/sig-actualizaciones'
    | '/api/wiki-chat'
    | '/'
    | '/clientes/documentacion'
    | '/cultura/conceptos'
    | '/cultura/objetivos'
    | '/cultura/politicas'
    | '/guardian/hallazgos'
    | '/procesos/revision'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/me/photo'
    | '/api/sync/checklist-clientes'
    | '/api/sync/clientes'
    | '/api/sync/documentacion'
    | '/api/sync/indicador-disponibilidad'
    | '/api/sync/proveedores'
    | '/api/sync/riesgos'
    | '/clientes'
    | '/cultura'
    | '/guardian'
    | '/procesos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/chat'
    | '/_authenticated/configuracion'
    | '/_authenticated/cronograma'
    | '/_authenticated/equipo'
    | '/_authenticated/indicadores'
    | '/_authenticated/normas'
    | '/_authenticated/proveedores'
    | '/_authenticated/riesgos'
    | '/api/chat'
    | '/api/checklist-clientes-estado'
    | '/api/hallazgos'
    | '/api/notificaciones'
    | '/api/sig-actualizaciones'
    | '/api/wiki-chat'
    | '/_authenticated/'
    | '/_authenticated/clientes/documentacion'
    | '/_authenticated/cultura/conceptos'
    | '/_authenticated/cultura/objetivos'
    | '/_authenticated/cultura/politicas'
    | '/_authenticated/guardian/hallazgos'
    | '/_authenticated/procesos/revision'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/me/photo'
    | '/api/sync/checklist-clientes'
    | '/api/sync/clientes'
    | '/api/sync/documentacion'
    | '/api/sync/indicador-disponibilidad'
    | '/api/sync/proveedores'
    | '/api/sync/riesgos'
    | '/_authenticated/clientes/'
    | '/_authenticated/cultura/'
    | '/_authenticated/guardian/'
    | '/_authenticated/procesos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChecklistClientesEstadoRoute: typeof ApiChecklistClientesEstadoRoute
  ApiHallazgosRoute: typeof ApiHallazgosRoute
  ApiNotificacionesRoute: typeof ApiNotificacionesRoute
  ApiSigActualizacionesRoute: typeof ApiSigActualizacionesRoute
  ApiWikiChatRoute: typeof ApiWikiChatRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiMePhotoRoute: typeof ApiMePhotoRoute
  ApiSyncChecklistClientesRoute: typeof ApiSyncChecklistClientesRoute
  ApiSyncClientesRoute: typeof ApiSyncClientesRoute
  ApiSyncDocumentacionRoute: typeof ApiSyncDocumentacionRoute
  ApiSyncIndicadorDisponibilidadRoute: typeof ApiSyncIndicadorDisponibilidadRoute
  ApiSyncProveedoresRoute: typeof ApiSyncProveedoresRoute
  ApiSyncRiesgosRoute: typeof ApiSyncRiesgosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cronograma': {
      id: '/_authenticated/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof AuthenticatedCronogramaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipo': {
      id: '/_authenticated/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AuthenticatedEquipoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/indicadores': {
      id: '/_authenticated/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof AuthenticatedIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/normas': {
      id: '/_authenticated/normas'
      path: '/normas'
      fullPath: '/normas'
      preLoaderRoute: typeof AuthenticatedNormasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proveedores': {
      id: '/_authenticated/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof AuthenticatedProveedoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/riesgos': {
      id: '/_authenticated/riesgos'
      path: '/riesgos'
      fullPath: '/riesgos'
      preLoaderRoute: typeof AuthenticatedRiesgosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checklist-clientes-estado': {
      id: '/api/checklist-clientes-estado'
      path: '/api/checklist-clientes-estado'
      fullPath: '/api/checklist-clientes-estado'
      preLoaderRoute: typeof ApiChecklistClientesEstadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hallazgos': {
      id: '/api/hallazgos'
      path: '/api/hallazgos'
      fullPath: '/api/hallazgos'
      preLoaderRoute: typeof ApiHallazgosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notificaciones': {
      id: '/api/notificaciones'
      path: '/api/notificaciones'
      fullPath: '/api/notificaciones'
      preLoaderRoute: typeof ApiNotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sig-actualizaciones': {
      id: '/api/sig-actualizaciones'
      path: '/api/sig-actualizaciones'
      fullPath: '/api/sig-actualizaciones'
      preLoaderRoute: typeof ApiSigActualizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wiki-chat': {
      id: '/api/wiki-chat'
      path: '/api/wiki-chat'
      fullPath: '/api/wiki-chat'
      preLoaderRoute: typeof ApiWikiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/documentacion': {
      id: '/_authenticated/clientes/documentacion'
      path: '/clientes/documentacion'
      fullPath: '/clientes/documentacion'
      preLoaderRoute: typeof AuthenticatedClientesDocumentacionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cultura/': {
      id: '/_authenticated/cultura/'
      path: '/cultura'
      fullPath: '/cultura/'
      preLoaderRoute: typeof AuthenticatedCulturaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cultura/conceptos': {
      id: '/_authenticated/cultura/conceptos'
      path: '/cultura/conceptos'
      fullPath: '/cultura/conceptos'
      preLoaderRoute: typeof AuthenticatedCulturaConceptosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cultura/objetivos': {
      id: '/_authenticated/cultura/objetivos'
      path: '/cultura/objetivos'
      fullPath: '/cultura/objetivos'
      preLoaderRoute: typeof AuthenticatedCulturaObjetivosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cultura/politicas': {
      id: '/_authenticated/cultura/politicas'
      path: '/cultura/politicas'
      fullPath: '/cultura/politicas'
      preLoaderRoute: typeof AuthenticatedCulturaPoliticasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guardian/': {
      id: '/_authenticated/guardian/'
      path: '/guardian'
      fullPath: '/guardian/'
      preLoaderRoute: typeof AuthenticatedGuardianIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guardian/hallazgos': {
      id: '/_authenticated/guardian/hallazgos'
      path: '/guardian/hallazgos'
      fullPath: '/guardian/hallazgos'
      preLoaderRoute: typeof AuthenticatedGuardianHallazgosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/procesos/': {
      id: '/_authenticated/procesos/'
      path: '/procesos'
      fullPath: '/procesos/'
      preLoaderRoute: typeof AuthenticatedProcesosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/procesos/revision': {
      id: '/_authenticated/procesos/revision'
      path: '/procesos/revision'
      fullPath: '/procesos/revision'
      preLoaderRoute: typeof AuthenticatedProcesosRevisionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/photo': {
      id: '/api/me/photo'
      path: '/api/me/photo'
      fullPath: '/api/me/photo'
      preLoaderRoute: typeof ApiMePhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/checklist-clientes': {
      id: '/api/sync/checklist-clientes'
      path: '/api/sync/checklist-clientes'
      fullPath: '/api/sync/checklist-clientes'
      preLoaderRoute: typeof ApiSyncChecklistClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/clientes': {
      id: '/api/sync/clientes'
      path: '/api/sync/clientes'
      fullPath: '/api/sync/clientes'
      preLoaderRoute: typeof ApiSyncClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/documentacion': {
      id: '/api/sync/documentacion'
      path: '/api/sync/documentacion'
      fullPath: '/api/sync/documentacion'
      preLoaderRoute: typeof ApiSyncDocumentacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/indicador-disponibilidad': {
      id: '/api/sync/indicador-disponibilidad'
      path: '/api/sync/indicador-disponibilidad'
      fullPath: '/api/sync/indicador-disponibilidad'
      preLoaderRoute: typeof ApiSyncIndicadorDisponibilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/proveedores': {
      id: '/api/sync/proveedores'
      path: '/api/sync/proveedores'
      fullPath: '/api/sync/proveedores'
      preLoaderRoute: typeof ApiSyncProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/riesgos': {
      id: '/api/sync/riesgos'
      path: '/api/sync/riesgos'
      fullPath: '/api/sync/riesgos'
      preLoaderRoute: typeof ApiSyncRiesgosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedCronogramaRoute: typeof AuthenticatedCronogramaRoute
  AuthenticatedEquipoRoute: typeof AuthenticatedEquipoRoute
  AuthenticatedIndicadoresRoute: typeof AuthenticatedIndicadoresRoute
  AuthenticatedNormasRoute: typeof AuthenticatedNormasRoute
  AuthenticatedProveedoresRoute: typeof AuthenticatedProveedoresRoute
  AuthenticatedRiesgosRoute: typeof AuthenticatedRiesgosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientesDocumentacionRoute: typeof AuthenticatedClientesDocumentacionRoute
  AuthenticatedCulturaConceptosRoute: typeof AuthenticatedCulturaConceptosRoute
  AuthenticatedCulturaObjetivosRoute: typeof AuthenticatedCulturaObjetivosRoute
  AuthenticatedCulturaPoliticasRoute: typeof AuthenticatedCulturaPoliticasRoute
  AuthenticatedGuardianHallazgosRoute: typeof AuthenticatedGuardianHallazgosRoute
  AuthenticatedProcesosRevisionRoute: typeof AuthenticatedProcesosRevisionRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedCulturaIndexRoute: typeof AuthenticatedCulturaIndexRoute
  AuthenticatedGuardianIndexRoute: typeof AuthenticatedGuardianIndexRoute
  AuthenticatedProcesosIndexRoute: typeof AuthenticatedProcesosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedCronogramaRoute: AuthenticatedCronogramaRoute,
  AuthenticatedEquipoRoute: AuthenticatedEquipoRoute,
  AuthenticatedIndicadoresRoute: AuthenticatedIndicadoresRoute,
  AuthenticatedNormasRoute: AuthenticatedNormasRoute,
  AuthenticatedProveedoresRoute: AuthenticatedProveedoresRoute,
  AuthenticatedRiesgosRoute: AuthenticatedRiesgosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientesDocumentacionRoute:
    AuthenticatedClientesDocumentacionRoute,
  AuthenticatedCulturaConceptosRoute: AuthenticatedCulturaConceptosRoute,
  AuthenticatedCulturaObjetivosRoute: AuthenticatedCulturaObjetivosRoute,
  AuthenticatedCulturaPoliticasRoute: AuthenticatedCulturaPoliticasRoute,
  AuthenticatedGuardianHallazgosRoute: AuthenticatedGuardianHallazgosRoute,
  AuthenticatedProcesosRevisionRoute: AuthenticatedProcesosRevisionRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedCulturaIndexRoute: AuthenticatedCulturaIndexRoute,
  AuthenticatedGuardianIndexRoute: AuthenticatedGuardianIndexRoute,
  AuthenticatedProcesosIndexRoute: AuthenticatedProcesosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChecklistClientesEstadoRoute: ApiChecklistClientesEstadoRoute,
  ApiHallazgosRoute: ApiHallazgosRoute,
  ApiNotificacionesRoute: ApiNotificacionesRoute,
  ApiSigActualizacionesRoute: ApiSigActualizacionesRoute,
  ApiWikiChatRoute: ApiWikiChatRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiMePhotoRoute: ApiMePhotoRoute,
  ApiSyncChecklistClientesRoute: ApiSyncChecklistClientesRoute,
  ApiSyncClientesRoute: ApiSyncClientesRoute,
  ApiSyncDocumentacionRoute: ApiSyncDocumentacionRoute,
  ApiSyncIndicadorDisponibilidadRoute: ApiSyncIndicadorDisponibilidadRoute,
  ApiSyncProveedoresRoute: ApiSyncProveedoresRoute,
  ApiSyncRiesgosRoute: ApiSyncRiesgosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
